name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build_essential
      run: sudo apt-get update && sudo apt-get install -y build-essential
    # install dependencies
    - name: metis 
      run: sudo apt-get install libmetis-dev
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev
      
    # build a project
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run:  cmake -B build -S .
    - name: cmake make
      run: cmake --build build/ --target all


  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen python3-pip -y
          pip install --upgrade pip
          pip install \
            sphinx==6.2.1 \
            breathe==4.35.0 \
            pydata-sphinx-theme==0.14.4 \
            sphinx-book-theme

      - name: Generate Doxygen XML
        run: |
          cd Documentation
          doxygen Doxyfile

      - name: Build Sphinx docs
        run: sphinx-build -b html Documentation docs/sphinx

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/sphinx
